### PR TITLE
Fix prototype pollution vulnerability

### LINKED ISSUE #68: 🚨 Potential Prototype Pollution
👋 Hello, @fiznool - a potential high severity Prototype Pollution vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-fiznool/body-parser-xml** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

### PR DESCRIPTION
**Pull request by yadhukrishnam**
Set the prototype of parsed xml object to undefined, so that prototype pollution is prevented.

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -43,7 +43,18 @@ module.exports = function (bodyParser) {
...
+          for (const key in xml) {
+            if (
+              key !== '__proto__' &&
+              key !== 'constructor' &&
+              key !== 'prototype'
+            ) {
+              safe[key] = xml[key];
+            }
+          }
+          req.body = safe || req.body;
```
Comment (fiznool) [inline index.js:57]: I think in this case it is fine to simply `delete` the offending keys.

```suggestion
          if(xml) {
            // Guard against prototype pollution
            delete xml.__proto__;
            delete xml.constructor;
            delete xml.prototype;
  
            req.body = xml;
          }
```

File: test.js [hunk 2]
```diff
@@ -130,4 +130,13 @@ describe('XML Body Parser', function () {
...
   });
+
+  it('should not set/change prototype', function (done) {
+    createServer();
+    request(app)
+      .post('/')
+      .set('Content-Type', 'application/xml')
+      .send('<__proto__><name>Bob</name></__proto__>')
+      .expect(200, { parsed: { name: ['Bob'] } }, done);
+  });
```
Comment (fiznool) [inline test.js:141]: Could we have tests for the `constructor` and `prototype` keys as well?

**Review by fiznool — CHANGES_REQUESTED** [review]
Do we need to sanitize nested objects as well? What about an XML payload of (e.g.)

``` xml
<foo>
  <bar>
    <__proto__>
      <name>Bob</name>
    </__proto__>
  </bar>
</foo>
```

From what I can gather about prototype pollution, it can happen if `__proto__` is overridden on any object?

File: test.js (hunk 2 above)
Comment (yadhukrishnam) [reply test.js]: Yeah. I have added tests for those too.

**Comment by fiznool** [comment]
> Do we need to sanitize nested objects as well?

Did you have any thoughts on this?

**Comment by yadhukrishnam** [comment]
> > Do we need to sanitize nested objects as well?
> 
> Did you have any thoughts on this?

I tested that. But doesn't seem to be vulnerable. The fix seems perfect for me now.

**Comment by fiznool** [comment]
CI is failing: need to run `npm run prettier` to fix. Once this is done and CI is passing I will merge in.

**Review by fiznool — COMMENTED** [review]
Thank you for the contribution, released as 2.0.3
